//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpha.Domain.Validators {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aplha.Domain.Validators.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O(a) Campo {0} deve ser maior que {1}..
        /// </summary>
        internal static string GreatherThan {
            get {
                return ResourceManager.GetString("GreatherThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O(a) Campo {0} está inválido..
        /// </summary>
        internal static string InvalidField {
            get {
                return ResourceManager.GetString("InvalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Há {0} vínculado com o {1}..
        /// </summary>
        internal static string LinkedWithOtherEntity {
            get {
                return ResourceManager.GetString("LinkedWithOtherEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O(a) {0} deve estár vinculado com o {1}..
        /// </summary>
        internal static string MustBeLinked {
            get {
                return ResourceManager.GetString("MustBeLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O(a) {0} está em processo de aprovação ou não está aprovado no sistema..
        /// </summary>
        internal static string NotApproved {
            get {
                return ResourceManager.GetString("NotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O(a) {0} não foi encontrado..
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} não está cadastrado em nossa base de dados.
        /// </summary>
        internal static string NotFoundInDb {
            get {
                return ResourceManager.GetString("NotFoundInDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O(a) {0} não está vínculado ao usuário logado..
        /// </summary>
        internal static string NotLinkedWithLoggedUser {
            get {
                return ResourceManager.GetString("NotLinkedWithLoggedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O(a) {0} é obrigatório..
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O(a) Campo {0} é obrigatório..
        /// </summary>
        internal static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O(a) {0} está com status não permitido para essa operação..
        /// </summary>
        internal static string StatusNotAllowed {
            get {
                return ResourceManager.GetString("StatusNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O(a) {0} já existe cadastrado no sistema..
        /// </summary>
        internal static string UniqueField {
            get {
                return ResourceManager.GetString("UniqueField", resourceCulture);
            }
        }
    }
}
